### ISSUE TITLE
Add Redis modules

### ISSUE THREAD

**Issue by brycelund** [mhassan1/redis-memory-server#10]
I'm looking for a way to load the Redis stack modules (primarily the [Redis JSON module](https://redis.io/docs/stack/json/#building-on-ubuntu-2004)). 
Is there a way this could be accomplished with the library as it is? (Perhaps through instance.args?) If not, any tips on how this would most easily be accomplished if I were to create a fork?

**Comment by mhassan1** [comment]
It seems like you should be able to accomplish this using `instance.args`:
```js
new RedisMemoryServer({
  instance: {
    args: ['--loadmodule', '/path/to/module/target/release/librejson.so']
  }
})
```
Of course, you will need to have the `librejson.so` file already built on the machine.
