### ISSUE TITLE
Command 'make' failed

### ISSUE THREAD

**Issue by andregosling** [mhassan1/redis-memory-server#28]
Hello. I'm deploying my node app using redis-memory-server at railway, and i'm getting this error:

```
#11 71.52 Downloading Redis stable: 0 % (0mb / 3.3mb)

#11 71.52 failed to download/install Redis binaries. The error: Error: Command failed: make

#11 71.52 sh: 1: cc: not found

#11 71.52     CC Makefile.dep

#11 71.52 sh: 1: cc: not found

#11 71.52 make[3]: cc: No such file or directory

#11 71.52 make[3]: *** [Makefile:270: alloc.o] Error 127

#11 71.52 make[2]: *** [Makefile:55: hiredis] Error 2

#11 71.52 make[1]: [Makefile:384: persist-settings] Error 2 (ignored)

#11 71.52     CC adlist.o

#11 71.52 /bin/sh: 1: cc: not found

#11 71.52 make[1]: *** [Makefile:436: adlist.o] Error 127

#11 71.52 make: *** [Makefile:6: all] Error 2

#11 71.52 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Do I gotta do something to install make and get this working?

In my local i didn't had to do anything, and I'm not really accustomed to this 'make', i guess it was probably installed by default on my Mac.

**Comment by mhassan1** [comment]
It says `cc: not found`. You'll need to install an OS dependency that provides `cc`.

**Comment by andregosling** [comment]
It might sound dumb, but how can I do such a thing in a deploy platform? I've never deal with this before.

**Comment by mhassan1** [comment]
These docs may help:
* https://docs.railway.app/deploy/builds#build-configuration
* https://nixpacks.com/docs/guides/configuring-builds#install-additional-packages

**Comment by andregosling** [comment]
I could't really get a good result. I've get one step back to try solve the problem, and I realised I'm only using this library for testing purposes. Technically, i doesn't even really need to install this on my deploy, because its never gonna be used. But, redis-memory-server is installed, so it try to downloads. Is there a way to prevent the lib to try the download only on my deployment, and keep it on my tests?

**Comment by mhassan1** [comment]
You can set the environment variable `REDISMS_DISABLE_POSTINSTALL=1`. You could also `yarn install --production`.

**Comment by andregosling** [comment]
It works. Thank you a lot for the help and for this library, it will be a game changer for my e2e tests that envolves my queue.
