### ISSUE TITLE
Error build Redis binary Apple Silicon

### ISSUE THREAD

**Issue by leandroandrade** [mhassan1/redis-memory-server#3]
For some reason, when download redis binary from https://download.redis.io/releases/redis-stable.tar.gz not working property.

Different behavior occur when the binaries are download from http://download.redis.io/redis-stable.tar.gz

Compare two binaries, they're different. I fixed this changing the location from binary will be downloaded when is stable version.

Has anyone seen this? 

S.O: MacOS BigSur
Version: 11.6
Make: 4.3

**Comment by mhassan1** [comment]
Interesting... I did not notice the difference between those two. Check this out:

```shell
$ curl -I https://download.redis.io/releases/redis-stable.tar.gz
-> last-modified: Sat, 27 Jun 2020 15:51:04 GMT

$ curl -I https://download.redis.io/redis-stable.tar.gz
-> last-modified: Wed, 21 Jul 2021 18:52:01 GMT
```

Seems we should be using the more recent version. I will create a PR.
