### ISSUE TITLE
Testing with Vitest opens a window in VSCode (Windows 10)

### ISSUE THREAD

**Issue by matheuslanduci** [mhassan1/redis-memory-server#39]
Hello,

I'm using `redis-memory-server` as an instance for my tests with `vitest` on Windows 10, and every time a test runs (and the server is killed), a script called redis_killer.js opens in my VSCode.

The tests run successfully; the only issue is that this file keeps opening. 

I don't know if this could be related, but I'm using `turbo` and a monorepo setup.

```typescript
// vitest.config.ts
import dotenv from 'dotenv'
import { defineConfig } from 'vitest/config'
import tsconfigPaths from 'vite-tsconfig-paths'

const env = dotenv.config({
	path: './.env.test'
})

if (env.error) {
	throw env.error
}

export default defineConfig({
	plugins: [tsconfigPaths()],
	test: {
		coverage: {
			provider: 'v8',
			exclude: [
				'drizzle.config.ts',
				'vitest.config.ts',
				'./src/main.ts',
				'./src/db/**/*.ts'
			]
		},
		environment: 'node',
		env: {
			...env.parsed
		},
		globals: true,
		include: ['./src/**/*.spec.ts'],
		setupFiles: ['./src/setup-tests.ts']
	}
})

```

```typescript
// setup-tests.ts
import { RedisMemoryServer } from 'redis-memory-server'
import Redis from 'ioredis'

const redisServer = new RedisMemoryServer()

// #resources/redis is a map to ./src/resources/redis
vi.mock('#resources/redis', async () => {
	return {
		redis: new Redis({
			port: await redisServer.getPort(),
			host: await redisServer.getHost()
		})
	}
})
```

![image](https://github.com/user-attachments/assets/982b93b5-0d72-4626-a132-2f5a6a7e0ee2)

**Comment by mhassan1** [comment]
I'm not able to replicate this locally. What command are you running to execute the tests?

Please add the following to the top of `setup-tests.ts` and let me know the result:
```js
console.log(process.env.NODE)
console.log(process.argv)
console.log(process.execPath)
```

**Comment by matheuslanduci** [comment]
I'm running the command `pnpm test` that goes to vitest
![image](https://github.com/user-attachments/assets/b4230c5f-cd25-4d3b-bc4e-44be880ecf03)

This is the output of the logs:
```bash
# process.env.NODE
C:\Users\Matheus Landuci\AppData\Local\pnpm\pnpm.exe

# process.argv
[
  'C:\\Program Files\\nodejs\\node.exe',
  'E:\\Workspaces\\Projects\\Project\\node_modules\\.pnpm\\tinypool@1.0.1\\node_modules\\tinypool\\dist\\entry\\process.js'
]

# process.execPath
C:\Program Files\nodejs\node.exe
```

Using Node.js 22.3.0 

If I try to run in a terminal (no VSCode running) it opens a new VSCode window with the file.

Things I tried:
- Reinstalled all packages
- Stop the instance before each test

**Comment by matheuslanduci** [comment]
Fixed it :) 

Since the `process.env.NODE` is different than the `process.argv`, I put a `NODE` env in my .env.test and the value is where my Node executable is that is 'C:\\Program Files\\nodejs\\node.exe' 

![image](https://github.com/user-attachments/assets/1664f96e-1cd1-4d4c-9515-700ddd758fb6)

Thanks.

**Comment by mhassan1** [comment]
Glad you found a workaround. Out of curiosity, what versions of `pnpm` and `vitest` are you using?

**Comment by matheuslanduci** [comment]
Using pnpm `9.9.0` and vitest `2.1.3`

**Comment by mhassan1** [comment]
The only way I can replicate this is by manually setting `process.env.NODE = 'C:\\path\\to\\pnpm'`, but that should never be set to something other than a `node` binary. If you can figure out where that is being set in your environment, that would be helpful. I can see where `pnpm` sets it to `process.execPath` (if it's not already set to something else): https://github.com/pnpm/npm-lifecycle/blob/1e0f149176877f906968a01087cf63290652ccbc/index.js#L81.
