### ISSUE TITLE
Lightweight cluster mode usage

### ISSUE THREAD

**Issue by kristof-kasa** [mhassan1/redis-memory-server#9]
Hey!

First of all, thank you for this amazing lib! 

My question is: 

Is there any way to use this in cluster mode? I don't want multiple nodes, just to test out a few simple things with Redis.Cluster.

Trying to search for binaries that might support it by default, but so far no luck.

**Comment by mhassan1** [comment]
The Redis [documentation](https://redis.io/docs/manual/scaling/#creating-and-using-a-redis-cluster) says:

> Note that the minimal cluster that works as expected must contain at least three master nodes.

That sounds a bit complicated for this library to set up, but I am open to ideas. It assumes a single spawned process, today.

**Comment by kristof-kasa** [comment]
I will start playing around with it how complicated it is :D my local docker setup for redis cluster is pretty fast with the startup time. I will try to reproduce the same.
As I see I should modify things [here](https://github.com/mhassan1/redis-memory-server/blob/main/src/util/RedisInstance.ts)

**Comment by itpropro** [comment]
Hey @kristof-kasa, did you had any success with your tests? Would love to use this library for some cluster tests as well.

**Comment by JCMais** [comment]
did anyone have any luck setting this up?
